site_name: "backstage-doc-sbx"
site_description: "Sandboxing the document creation template"
repo_url: https://github.com/jasperja/backstage-sbx
edit_uri: edit/main/docs

nav:
  - Introduction: index.md

plugins:
  - techdocs-core